### ISSUE TITLE
Skematik Seven Segment gada

### ISSUE THREAD

**Issue by nanaperm12** [FansElectronics/Jadwal-Waktu-Sholat-Simple-7-Segment#1]
assalamualaikum wr wb, mohon izin kang sebelumnya saya mau coba codingannya ini, tapi saya masih bingung untuk skematik ke seven segment nya, saya cari cari disini gada, boleh ga sekiranya share skematiknya ?

**Comment by Vean** [comment]
Baru respon karena ini project lama dan tidak ada notif disaya. Skematik sudah saya upload dalam bentuk PDF. untuk file eagle silahkan redesign ulang. cek disini https://github.com/FansElectronics/Jadwal-Waktu-Sholat-Simple-7-Segment/commit/eb1e01c4f5ed2c2e277d8b3c0953be2e1dce974a
